In [7]:

import json, pandas as pd
from pathlib import Path
from dateutil import parser as dateparser

pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 120)

records = []

path = "C:\\Users\\Asus\\Downloads\\used_cars_train.json"
f = open(path)

for l in f:
    d = json.loads(l)
    records.append(d)

f.close()

df = pd.DataFrame(records)
df.head(6)

,id,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,size,type,paint_color,state,posting_date
0,7314977535,4000,2007.0,jeep,grand cherokee limited,good,8 cylinders,gas,278000.0,clean,automatic,4wd,mid-size,SUV,silver,or,2021-04-30T12:43:00-0700
1,7314789720,4800,2006.0,chevrolet,silverado,good,8 cylinders,gas,260600.0,clean,automatic,rwd,full-size,pickup,white,fl,2021-04-30T10:31:34-0400
2,7304863686,5500,2007.0,toyota,yaris,excellent,4 cylinders,gas,51000.0,clean,manual,fwd,compact,hatchback,blue,al,2021-04-10T15:11:21-0500
3,7311469964,26990,2016.0,chevrolet,express commercial cutaway,good,8 cylinders,gas,75734.0,clean,automatic,rwd,full-size,truck,white,wi,2021-04-23T13:13:09-0500
4,7305988194,48995,2020.0,toyota,tundra limited 4x4,like new,8 cylinders,gas,20000.0,lien,automatic,4wd,full-size,truck,silver,nm,2021-04-12T20:01:35-0600
5,7315190187,1850,2002.0,volkswagen,jetta gls,good,4 cylinders,gas,240000.0,clean,manual,fwd,mid-size,sedan,black,ca,2021-04-30T23:01:08-0700

In [8]:
df = pd.DataFrame(records)

In [9]:
df.head(6)

,id,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,size,type,paint_color,state,posting_date
0,7314977535,4000,2007.0,jeep,grand cherokee limited,good,8 cylinders,gas,278000.0,clean,automatic,4wd,mid-size,SUV,silver,or,2021-04-30T12:43:00-0700
1,7314789720,4800,2006.0,chevrolet,silverado,good,8 cylinders,gas,260600.0,clean,automatic,rwd,full-size,pickup,white,fl,2021-04-30T10:31:34-0400
2,7304863686,5500,2007.0,toyota,yaris,excellent,4 cylinders,gas,51000.0,clean,manual,fwd,compact,hatchback,blue,al,2021-04-10T15:11:21-0500
3,7311469964,26990,2016.0,chevrolet,express commercial cutaway,good,8 cylinders,gas,75734.0,clean,automatic,rwd,full-size,truck,white,wi,2021-04-23T13:13:09-0500
4,7305988194,48995,2020.0,toyota,tundra limited 4x4,like new,8 cylinders,gas,20000.0,lien,automatic,4wd,full-size,truck,silver,nm,2021-04-12T20:01:35-0600
5,7315190187,1850,2002.0,volkswagen,jetta gls,good,4 cylinders,gas,240000.0,clean,manual,fwd,mid-size,sedan,black,ca,2021-04-30T23:01:08-0700

In [10]:
df.shape

(71275, 17)

In [11]:
df.dtypes

id                int64
price             int64
year            float64
manufacturer        str
model               str
condition           str
cylinders           str
fuel                str
odometer        float64
title_status        str
transmission        str
drive               str
size                str
type                str
paint_color         str
state               str
posting_date        str
dtype: object

In [12]:
categorical_cols = ["manufacturer", "model", "fuel", "transmission", "drive", "state", "type", "paint_color", "title_status"]

In [13]:
for c in categorical_cols:
    if c in df.columns:
        df[c] = df[c].astype("category")

In [14]:
quant_cols = ["price", "year", "odometer"]
df[categorical_cols + quant_cols].head()

,manufacturer,model,fuel,transmission,drive,state,type,paint_color,title_status,price,year,odometer
0,jeep,grand cherokee limited,gas,automatic,4wd,or,SUV,silver,clean,4000,2007.0,278000.0
1,chevrolet,silverado,gas,automatic,rwd,fl,pickup,white,clean,4800,2006.0,260600.0
2,toyota,yaris,gas,manual,fwd,al,hatchback,blue,clean,5500,2007.0,51000.0
3,chevrolet,express commercial cutaway,gas,automatic,rwd,wi,truck,white,clean,26990,2016.0,75734.0
4,toyota,tundra limited 4x4,gas,automatic,4wd,nm,truck,silver,lien,48995,2020.0,20000.0

In [15]:
df[categorical_cols ].head()

  manufacturer                       model fuel transmission drive state       type paint_color title_status
0         jeep      grand cherokee limited  gas    automatic   4wd    or        SUV      silver        clean
1    chevrolet                   silverado  gas    automatic   rwd    fl     pickup       white        clean
2       toyota                       yaris  gas       manual   fwd    al  hatchback        blue        clean
3    chevrolet  express commercial cutaway  gas    automatic   rwd    wi      truck       white        clean
4       toyota          tundra limited 4x4  gas    automatic   4wd    nm      truck      silver         lien

In [16]:
df[ quant_cols].head()

   price    year  odometer
0   4000  2007.0  278000.0
1   4800  2006.0  260600.0
2   5500  2007.0   51000.0
3  26990  2016.0   75734.0
4  48995  2020.0   20000.0

In [17]:



brand_counts = df["manufacturer"].value_counts(dropna=True)
brand_counts.head(20)

manufacturer
ford             13942
chevrolet        10887
toyota            6339
honda             4367
nissan            3576
jeep              2899
gmc               2853
ram               2580
dodge             2271
bmw               1975
subaru            1802
mercedes-benz     1729
hyundai           1561
volkswagen        1551
kia               1266
chrysler          1221
lexus             1121
cadillac          1098
buick              931
mazda              889
Name: count, dtype: int64